version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - app-network
    depends_on:
      - surrealdb
      - redis
    env_file:
      - .env
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    command: start --log trace --user startup --pass eHmBXR+0O38Q6HixRmTh+u7t2MT+yXHrE3M52UAh6vU= file:data/surrealdb.db
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - surrealdb-data:/data
    networks:
      - app-network
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    volumes:
      - redis-data:/data
volumes:
  surrealdb-data:
  redis-data:
networks:
  app-network:
    driver: bridge